import {HOME,ADD,LEADER,NONE} from "../actions/navigation";

/**
 * @description Reducer for navigation bar. Updates the activeTab state in accordance with action being generated
 * @function
 * @param {object} state - the state of Redux store
 * @param {object} action - the action generated by action generator
 * @returns {{activeTab: null}|{activeTab: string}}
 */
const navReducer = (state={activeTab:null},action)=>{

    switch (action.type){
        case HOME:
            return {
                activeTab:'Home'
            }
        case ADD:
            return {
                activeTab:'New Question'
            }
        case LEADER:
            return {
                activeTab:'Leader Board'
            }
        case NONE:
            return {
                activeTab:null
            }
        default:
            return state
    }
}

export default navReducer;